### ISSUE TITLE
Support Arbitrary IMU Orientation

### ISSUE THREAD

**Issue by superjax** [rosflight/firmware#148]
I had to mount my naze for my autogyro upside down.  How do I fly?

**Comment by TimWhiting** [comment]
Wondering what the status of this issue is, because our team has the naze upside down on the foamy... Can I help get this working?

**Comment by TimWhiting** [comment]
I looked into the branch for this fix. It looks like you were planning on supporting any arbitrary angle for the orientation. Is that necessary or could we just multiply the raw imu input by -1 based on an orientation parameter in the x y and z axis?

**Comment by superjax** [comment]
Sort of. You have to multiply both the z and y axes by -1, (otherwise you'll end up with a left-handed coordinate frame).  Since there are so many configurations to consider, it just made sense to support arbitrary orientations.  There is actuallly a pull request active on this one, which adds 3 parameters.  If you merged `master` into that branch, it would probably work.

**Comment by legoabram** [comment]
I had to make a small tweak, but I have it working now. The parameters say degrees, but everything is treated like radians. I figured degrees made more sense in this context, so I added a scalar. I've also made a few organization changes to match what I've been seeing elsewhere in the code. If you would allow it, how may I submit my changes?

**Comment by superjax** [comment]
Why don't you submit a pull request and put me as a reviewer?

**Comment by superjax** [comment]
Finished!
