### ISSUE TITLE
MOTOR_PWM_UPDATE param default value

### ISSUE THREAD

**Issue by dpkoch** [rosflight/firmware#165]
@superjax Currently the default value for the `MOTOR_PWM_UPDATE` default value is 490... should that be 400? I assume this is the update rate in Hz (400Hz for SimonK speed controllers)?

**Comment by superjax** [comment]
490 is right.  Simon K supports "up to 500Hz" (because 2000 us is 500Hz). To give us some wiggle room, I chose 490.
