### ISSUE TITLE
Arms on boot up if R/C transmitter is not on

### ISSUE THREAD

**Issue by wynn4** [rosflight/firmware#167]
When I power up the board and the R/C transmitter is switched off, the board Arms and stays armed until I switch on my transmitter.  I'm using a PPM receiver which has failsafes set such that when the receiver gets no signal from the transmitter, it defaults to outputting 'disarmed' on the arm channel.  Once I have turned on my R/C transmitter, but then switch it off again (which puts the receiver into failsafe mode) the board stays disarmed as expected.  Also if I arm the board with the transmitter on and then switch off the transmitter, the board disarms as expected.

**Comment by superjax** [comment]
I can't replicate this on my flip32+ and an orange R618XL in PPM mode.  What receiver are you using, and what is the failsafe behavior set to?

**Comment by dpkoch** [comment]
Slightly different, but might be related:

Using a CPPM receiver, if I power both the naze and the receiver at the same time (through the RC power rail), the red light comes on at boot, but the naze isn't armed. If I then set the `ARM_CHANNEL` param, the light goes off which suggest that `init_rc` might affect this somehow.

If I power the naze through USB, then power the receiver through the RC rail, the red light does not come on.

**Comment by dpkoch** [comment]
Let's just verify this with @wynn4 and his setup before we actually close this; he was saying that his actually got armed. This may have fixed it, but let's just double check.
