### ISSUE TITLE
Default mixer should be invalid

### ISSUE THREAD

**Issue by dpkoch** [rosflight/firmware#170]
Right now the default value for `PARAM_MIXER` is `QUADCOPTER_X`. However, I think it would be better if it started as something invalid, so that the user is forced to select the correct mixer before the autopilot will arm.

@superjax do you agree?

**Comment by superjax** [comment]
I don't know.  You're probably right though.  It is really scary when you try to fly a multirotor on the wrong mixer.  (I've tried, more than I care to admit, because I didn't realize the mixer was wrong).
