### ISSUE TITLE
Check for calibration before arming

### ISSUE THREAD

**Issue by dpkoch** [rosflight/firmware#171]
I think we should check that an IMU calibration has been performed before the autopilot will arm. The easiest way to do this is to check if all of the calibration parameters are zero (their default value).

If someone tried to lift off with a multirotor without calibrating it wouldn't be too great; this would prevent that.

@superjax what do you think?

**Comment by superjax** [comment]
It's actually not a huge deal in general, I fly manually all the time without calibrating, and just take care of it in stick trim.  You're right though, it'll mess up onboard computer commands.

I don't know. I don't want to make annoying to fly, adding additional steps could do that, but I'm not sure.

**Comment by dpkoch** [comment]
Yeah, being annoying is a fair point. I'm not sure if it'd be too bad, since you just have to set it down level and then call the calibration service (or push the button in the ground station!). You'd also only really have to do it once after you flash new firmware, then the calibration would stick around forever unless you notice bad performance and decide to redo it. I could go either way though.

**Comment by superjax** [comment]
That's right.  I like the idea that once you've at least done one calibration then it should work on boot up every time after that.
