### ISSUE TITLE
Add parameter for calibrating gyros on arm

### ISSUE THREAD

**Issue by dpkoch** [rosflight/firmware#172]
@superjax We removed calibrating gyros on arm to fix #166, which I think is generally the right behavior. However, for multirotors it'd be really convenient to have that happen. What if we add a parameter that you can set to turn on gyro calibration when armed, which would be set to off by default?

**Comment by superjax** [comment]
I think that is a great idea.  It's a cool feature, but it has issues with fixedwings.  Sounds good.
