### ISSUE TITLE
rc_override doesn't activate with x/y deviation

### ISSUE THREAD

**Issue by len0rd** [rosflight/firmware#198]
While using the new status message, I noticed that when in autopilot mode, rc_override would only switch to true if I deviated yaw, but not if I deviated roll/pitch. This would be hard to catch without the fixed status message, since the old message would not accurately display rc_override state.

**Comment by superjax** [comment]
This is addressed by #199

**Comment by len0rd** [comment]
pretty sure this is fixed in C++ implementation
