### ISSUE TITLE
Tests fail if compiled in release mode

### ISSUE THREAD

**Issue by superjax** [rosflight/firmware#202]
Weird, huh?

**Comment by plusk01** [comment]
What kind of tests? Are you using `std::fabs`? Are you using `-ffast-math` ?

I've had numerical tests fail with `-ffast-math` and `-std::fabs`; but with `-ffast-math` and `std::abs` it works as expected. For me, `-ffast-math` and `-O3` was optimizing out some floating point based predicates in some decision logic.

**Comment by superjax** [comment]
It was a weird optimization of the `if` loop surrounding the accel update.
