### ISSUE TITLE
Crazy servo output when aircraft is disarmed

### ISSUE THREAD

**Issue by dpkoch** [rosflight/firmware#217]
Original post by @dallinbriggs:

I think something may be wrong with the servo output while sitting disarmed. Having a high pwm update rate causes the servo output to be completely random. In this plot, all I did was switch the update rate from the default frequency to 50 Hz for servos. 

![servo_output](https://user-images.githubusercontent.com/3312740/28472502-08cd91de-6dfe-11e7-92f5-04d635b113e4.jpg)

**Comment by dpkoch** [comment]
@dallinbriggs It appears that this behavior only occurs when the autopilot is in failsafe mode. This happens because the failsafe command is zero setpoints in angle mode, so the attitude controller is running. Can you confirm that this stops happening if you have RC on?

**Comment by dpkoch** [comment]
@dallinbriggs Can you confirm that #218 fixes this issue?

**Comment by superjax** [comment]
closed by #218
