### ISSUE TITLE
turbotrig fast_alt

### ISSUE THREAD

**Issue by len0rd** [rosflight/firmware#219]
I plugged everything into matlab and here are the results. The red line is using fast_alt's current array/equation, and the blue line is using the equation we talked about [here](https://en.wikipedia.org/wiki/Pressure_altitude). There is a decent amount of deviation, but it'd probably be best to have my work checked before we proceed with any changes.
![press-alt](https://user-images.githubusercontent.com/15990762/28479711-dbe73ea0-6e1a-11e7-9464-103c758efed3.png)
[fast_alt_matlab.zip](https://github.com/rosflight/firmware/files/1166589/fast_alt_matlab.zip)

**Comment by superjax** [comment]
It appears that I made the lookup table wrong.  Let's just re-do it.  I have some code that quickly generates C code for lookup tables from standard functions.

https://gist.github.com/superjax/625d2242ea605057e685c3fbaf0722c7
