### ISSUE TITLE
IMU intermittently stops responding

### ISSUE THREAD

**Issue by BillThePlatypus** [rosflight/firmware#266]
Seen with a Naze 32, connected to an odroid.  The IMU stops responding for up to 2 seconds.  The airspeed sensor is connected; this may be related.

**Comment by BillThePlatypus** [comment]
Tried replicating the issue with with no sensors attached, but it worked fine

**Comment by BillThePlatypus** [comment]
Now trying with an airspeed sensor attached.  I am using rostopic to print the IMU and airspeed information, and so far there is no issue.  I'll leave it overnight.

**Comment by BillThePlatypus** [comment]
No problem overnight.  Next I'll try with an RC receiver as well

**Comment by superjax** [comment]
That is good news.  Let's try it now with the airspeed sensor connected to the plane, (just use some jumpers to extend it out to the new board and see if we can determine where the problem might be coming from)

**Comment by BillThePlatypus** [comment]
This might be related.  I was testing the bug on the plane that originally showed it.  It was working fine for a while, but then the IMU completely stopped responding.  As I write this, I flipped the autopilot switch on the RC to get a timestamp for comparison, (4 minutes later) and that caused the IMU to start responding again,  then stop for .003 s, and then start again.

**Comment by BillThePlatypus** [comment]
I just saw the recommendation to use the airspeed sensor from the plane on the new board.  I was trying to solder on headers for the RC connection and bridged  a 5V and ground pin, so I'll have to fix that before powering up the other board.

**Comment by BillThePlatypus** [comment]
Also, it just lost RC for .02 seconds, and thinks that there is a sonar.
