### ISSUE TITLE
Discussion forum, reCAPTCHA not set up

### ISSUE THREAD

**Issue by korken89** [rosflight/firmware#273]
Hi, it seems it's currently impossible to register to the discuss.rosflight.org
The reCAPTCHA has not been setup so one cannot finish the registration for now.

Screenshot:
![image](https://user-images.githubusercontent.com/913109/33446410-3e101046-d600-11e7-8f89-ea76ba3cfd8d.png)

**Comment by superjax** [comment]
Haha!  It looks like recaptcha.net is down.

Unfortunately, the only way to register is with google.  Does it work now?

**Comment by korken89** [comment]
Yeah, works fine with Google :)
