### ISSUE TITLE
Differentiate IMU after integration

### ISSUE THREAD

**Issue by superjax** [rosflight/firmware#281]
I was talking with Walt at inertialsense today, and he had an awesome idea about how to reduce noise on IMU measurements.

What he suggested is to integrate IMU at full rate, then differentiate it at the rate that we request measurements.  This will give us a filtered version of our IMU data, that contains all the information possible.

**Comment by superjax** [comment]
This has been integrated into #278

**Comment by rosflight-admin** [comment]
This issue has been mentioned on **ROSflight**. There might be relevant details there:

https://discuss.rosflight.org/t/rostopics-accessing-estimates-from-estimator/48/2
