### ISSUE TITLE
F3 Support Planned?

### ISSUE THREAD

**Issue by atyshka** [rosflight/firmware#299]
This looks like I really cool project and I'd love to use it as a cheap, simple way to create a ROS quadcopter. However, it is my understanding that only F1 boards are supported as of now. It looks like F4 support is currently in development, but does that mean that there are no plans for F3 support? I'd hate to have to buy an older, slower FC to use rosflight.

**Comment by superjax** [comment]
Hey @atyshka!  Thanks for the interest!

Theoretically, we just need an F3 driver layer that implements the [`board`](https://github.com/rosflight/firmware/blob/master/include/board.h) interface.  Right, we are using [`breezystm32`](https://github.com/rosflight/breezystm32) as the F1 driver, and [`airbourne`](https://github.com/rosflight/airbourne) for F4.

We've talked about using @plusk01's [`airdamon_f3`](https://github.com/plusk01/airdamon_f3) as the F3 backend, but we are focused on the F4 port for now.  `airdamon` and `airbourne` are super similar (does the name give it away?)
