### ISSUE TITLE
Feature request: Split yaw LPF from the rest so one can tune its filter independently

### ISSUE THREAD

**Issue by korken89** [rosflight/firmware#307]
In a system I am currently working on excessive noise in the yaw axis is causing problems, and I have currently solved it by manually setting the yaw rate LPF manually in the code.
To this end, I'd like to request that the yaw rate LPF can be tuned by its own, and not be locked to the other axises.

The rationale is the the yaw axis has generally way less bandwidth than the roll and pitch axises and to reflect this, and since the yaw controller generally has a lot higher gains than the roll and pitch controllers, more aggressive filtering of yaw can be needed.

What are the thoughts from the devs on this?

**Comment by superjax** [comment]
That's a good idea.  @dpkoch, what do you think?

It's a relatively straight-forward adjustment.  I'll code up a prototype.

**Comment by dpkoch** [comment]
Closed by #308
