### ISSUE TITLE
Fix reporting RC values in the 0 to 1000 range

### ISSUE THREAD

**Issue by dpkoch** [rosflight/firmware#370]
Right now we're reporting RC values (as published on `rc_raw`) in the 0 to 1000 range, instead of in the 1000 to 2000 range. This has been causing people confusion.

It may be a rosflight_io thing, but off the top of my head I think it was a change to the firmware that made the change.

We should either revert to 1000 to 2000, or (maybe better?) report floating point from 0 to 1 or -1 to 1 or something. Do you have thoughts @superjax?

We also need to make sure the documentation is consistent with what we're reporting.

**Comment by Georacer** [comment]
IMHO, floating point values are a bad choice for reporting raw values, especially for outputs.
You cannot control whether they correspond to a control surface servo (-1,1) makes sense or a motor (0,1) makes sense.

It's better to report the raw uS value and let the user decode the right meaning for his application.
