### ISSUE TITLE
Changing MIXER causes RC values to read incorrectly

### ISSUE THREAD

**Issue by jbwillis** [rosflight/firmware#372]
Using the current `master` branch with the default parameter configuration, I am having the `/rc_raw` values jump to being between `985-989` after changing the MIXER parameter with the sticks centered and throttle down. I am using an frsky D4R-II receiver connected to an OpenPilot Revo via PPM. 

Talking with @dpkoch and @BillThePlatypus we think it is likely due to the `pwm_init` function being called every time the MIXER parameter gets changed. This could be causing changes to the timer configuration for the timer used for reading the PPM.

One note, this caused the throttle to jump to 100% and the arm switch value to jump to 100% and hang regardless of the values on the controller. Luckily the vehicle I was working with wasn't armed when the MIXER switch was made, otherwise it would have been entirely uncontrollable.

**Comment by BillThePlatypus** [comment]
When you say it wasn't armed, do you mean that there was some sort of physical switch disconnecting the motors? Could this cause an disarmed plane to arm itself?

**Comment by jbwillis** [comment]
By not armed, I mean that rosflight was not in the armed state.

**Comment by BillThePlatypus** [comment]
That is a safety issue. You don't want a disarmed aircraft arming itself, especially when it can simultaneously misread the throttle command.

**Comment by BillThePlatypus** [comment]
I've replicated the issue. I'm surprised we haven't seen this yet.

**Comment by jbwillis** [comment]
It might be worth working back through the history of rosflight and
airbourne to see if there’s a change that broke it.
