### ISSUE TITLE
Documentation parameter PARAM_ARM_STICKS doesn't exist

### ISSUE THREAD

**Issue by Georacer** [rosflight/firmware#375]
Hello everyone!

In the parameter documentation (https://docs.rosflight.org/user-guide/parameter-configuration/) for ARM_CHANNEL, in its comments a parameter PARAM_ARM_STICKS is referred to but doesn't exist.
It didn't exist for an appreciable amount of time, as far as I scanned git history.

Is it implied that setting ARM_CHANNEL>-1 disables stick arming?

**Comment by BillThePlatypus** [comment]
Yes, setting `ARM_CHANNEL` > -1 disables stick arming. The `ARM_STICKS` parameter is no longer used. I'll take it out of the documentation.

**Comment by Georacer** [comment]
Thanks for the clarification!
